default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: copa_cc

test:
  <<: *default
  database: copa_cc

production:
  <<: *default
  database: copa_cc
  socket: /var/lib/mysql/mysql.sock
#  password: <%= ENV['COPA-COCA-COLA_DATABASE_PASSWORD'] %>
