defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["TW_COPA_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["TW_COPA_CONSUMER_SECRET"] %>

test:
  <<: *defaults

production:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV["TW_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["TW_CONSUMER_SECRET"] %>
